### ISSUE TITLE
Take groene wandeling into network profile for brussels.

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#11]
> De routeplanner lijkt de groene wandeling niet als optie mee te nemen in “netwerken” ? staat op dezelfde hoogte als een GFR.

**Comment by xivk** [comment]
@pietervdvn can you check what's going on with the route? It looks like this is not taken into account? 

https://routing.anyways.eu/projects/bikeforbrussels/#15.84/50.7744/4.3553?sb=true&o=4.3572358,50.7741334&d=4.3423890,50.7852445&p=profile1

It's possibly due to this footway, part of the network:

https://www.openstreetmap.org/way/25215399#map=21/50.77398/4.35416&layers=T

**Comment by pietervdvn** [comment]
It is due to these steps: https://www.openstreetmap.org/way/438212409
