### ISSUE TITLE
Add an edit-here-in-osm button

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#13]
It would be really awesome to add a edit-here-in-osm button. Perhaps something that can be in the attribution link:

![image](https://user-images.githubusercontent.com/1128068/76339837-ef0a5800-62fa-11ea-808f-ca3561fce427.png)

We need a link like this, just use the zoom/center of the map:

https://www.openstreetmap.org/edit#map=19/50.84872/4.32168

**Comment by pietervdvn** [comment]
Adding this to the attribution is a real pain in the ass and borderline impossible... I'll have a look for a different option

**Comment by xivk** [comment]
I do think this is quite possible:

https://docs.mapbox.com/mapbox-gl-js/api/#attributioncontrol

Use the custom attribution, add a link with a class or id, and update the url on a map view change.

**Comment by pietervdvn** [comment]
The custom text shows ugly newlines between them. I opted for a small edit-button in the bottom-left for now

**Comment by pietervdvn** [comment]
I always forget that weird layout issues can be solved using css...

There is a small 'edit' pencil in the attribution now, clicking it will link you through to OSM.

There is no functionality to directly go to shortcut right now, if the routeplanning source is shortcut.
