### ISSUE TITLE
Update profiles

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#15]
Update profiles:

- Gebalanceerd -> Recreatief
- Snelst -> Commute

**Comment by xivk** [comment]
Changed the profile descriptions in NL and EN. Please test them here:

https://staging.anyways.eu/projects/bikeforbrussels/

I'll ask @jbelien very nicely and I'm sure he will have look at the FR once we have validate the NL and EN texts.

Can you check @Driesvanransbeeck and @pietervdvn

**Comment by jbelien** [comment]
Just noticed that the "Van ... Naar ..." always stays in Dutch when you change to English or French.

![image](https://user-images.githubusercontent.com/1150563/78243997-0fd26180-74e5-11ea-88ba-f3802dc40fb6.png)
