### ISSUE TITLE
Weird routes

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#28]
https://routeplanner.bike.brussels/#13.72/50.8649/4.3152?sb=true&o=4.3220772,50.8698411&d=4.3106358,50.8581213&p=profile1

![image](https://user-images.githubusercontent.com/1128068/83547011-81388b80-a4f9-11ea-8ccb-28837be1deca.png)

**Comment by xivk** [comment]
This is a problem with us completely excluding primary roads:

https://routeplanner.bike.brussels/#16.88/50.86180/4.31651?sb=true&o=4.3168491,50.8626573&d=4.3150098,50.8615379&p=profile1

![image](https://user-images.githubusercontent.com/1128068/83620601-6f9cc580-a585-11ea-80b4-cce497ab0fab.png)

**Comment by xivk** [comment]
In this case this road looks reasonable:

https://www.mapillary.com/app/?pKey=obClReV5QumT2gmApfe9jA&focus=photo&lat=50.86330801&lng=4.31749205&z=17

**Comment by xivk** [comment]
This is probably a duplicate of #32

**Comment by pietervdvn** [comment]
Fixed by the primary roads allowed update
