### ISSUE TITLE
Avoiding all primary roads needs to be toned down

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#32]
![image](https://user-images.githubusercontent.com/1128068/80242526-64d54380-865d-11ea-8ed1-5cd3bfeb9063.png)

https://routeplanner.bike.brussels/#16.06/50.86922/4.32209?sb=true&o=4.3199160,50.8670008&d=4.3206522,50.8675420&p=profile1

**Comment by pietervdvn** [comment]
This is a case of "not going over primaries without cycleway".

I'm working on a fix via the aspected profiles.

**Comment by xivk** [comment]
#31 is a duplicate:

https://routing.anyways.eu/projects/bikeforbrussels/#15.39/50.8594/4.3167?sb=true&o=4.3191997,50.8609914&d=4.3238259,50.8618728&p=profile1

**Comment by xivk** [comment]
#36 is another duplicate:

https://routing.anyways.eu/projects/bikeforbrussels/#15.10/50.8568/4.3463?sb=true&o=4.3502207,50.8568528&d=4.3443745,50.8599416&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84432671-0e2fc300-ac25-11ea-97ae-d4d717a3ea45.png)

**Comment by xivk** [comment]
Probably also related:

![image](https://user-images.githubusercontent.com/1128068/84652397-758a9300-af03-11ea-815b-62fd9bf53173.png)

https://routing.anyways.eu/projects/bikeforbrussels/#16.50/50.82724/4.29353?sb=true&o=4.2928331,50.8275102&d=4.2925344,50.8266447&p=profile1

**Comment by pietervdvn** [comment]
All fixed after the update which allows primary roads
