### ISSUE TITLE
Small part of roundabout no accessible

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#39]
![image](https://user-images.githubusercontent.com/1128068/84438549-a2525800-ac2e-11ea-82d0-afc586c2ba68.png)

https://routeplanner.bike.brussels/?sb=true&o=4.3317550,50.8767605&d=4.3979127,50.8699507&p=profile1#17.33/50.87474/4.33286?sb=true&o=4.3334655,50.8750271&d=4.3336134,50.8745367&p=profile1

**Comment by xivk** [comment]
@pietervdvn It looks like this segment cannot be accessed:

https://www.openstreetmap.org/way/530562411

Same for this:

https://www.openstreetmap.org/way/351522286

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/84802292-ad2b3500-b000-11ea-8443-aff78fb5267e.png)
Fixed by the new routing profile
