### ISSUE TITLE
Detour to avoid roundabout

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#41]
https://routing.anyways.eu/projects/bikeforbrussels/#16.59/50.81876/4.42845?sb=true&o=4.4266268,50.8171302&d=4.4243225,50.8195326&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84649589-afa56600-aefe-11ea-9b4f-579b7776d20e.png)

**Comment by pietervdvn** [comment]
Fixed too with the latest profile update
