### ISSUE TITLE
Access restrictions don't match network.

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#42]
https://routing.anyways.eu/projects/bikeforbrussels/#15.49/50.8087/4.2825?sb=true&o=4.2775414,50.8089876&d=4.2823999,50.8108316&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84704429-b7422a80-af51-11ea-836a-4c8b61e550ff.png)

**Comment by pietervdvn** [comment]
Is fixed now: 
![image](https://user-images.githubusercontent.com/1466478/84795958-68030500-aff8-11ea-896b-89223784b8ef.png)
