### ISSUE TITLE
Route 5 has to go via main road

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#44]
This route:

![image](https://user-images.githubusercontent.com/1128068/84775484-3463b300-afd7-11ea-970e-d20804814b9b.png)

Has to move to the main road:

![image](https://user-images.githubusercontent.com/1128068/84775585-50675480-afd7-11ea-95a9-6112fd95e384.png)

Original message:

![image](https://user-images.githubusercontent.com/1128068/84775646-6117ca80-afd7-11ea-9d00-a10af24b9ad9.png)

**Comment by pietervdvn** [comment]
Updated here: https://www.openstreetmap.org/changeset/86730817

**Comment by xivk** [comment]
Keep open until fixed in the route planner.
