### ISSUE TITLE
Route 6 has to go via main road

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#45]
Route 6 has to move to the main road for this section:

https://routing.anyways.eu/projects/genk/#14.56/50.9736/5.5097?sb=true&o=5.5125180,50.9774172&d=5.5026376,50.9677320&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84775998-ae943780-afd7-11ea-9e37-7b31e1c7124c.png)

This is the desired route:

https://routing.anyways.eu/projects/genk/#14.56/50.9736/5.5097?sb=true&o=5.5125180,50.9774172&d=5.5026376,50.9677320&p=profile3

![image](https://user-images.githubusercontent.com/1128068/84776068-c5d32500-afd7-11ea-9f09-58b189c5f858.png)

**Comment by pietervdvn** [comment]
Updated here: https://www.openstreetmap.org/changeset/86731415#map=16/50.9724/5.5093

**Comment by xivk** [comment]
Keep open until fixed.
