### ISSUE TITLE
Route 4 via Henri Esserslaan

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#46]
Instead of this route:

https://routing.anyways.eu/projects/genk/#15.77/50.9825/5.4888?sb=true&o=5.4933187,50.9834613&d=5.4825810,50.9828498&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84776368-1f3b5400-afd8-11ea-8a83-1e91fa60578f.png)

We need this route:

https://routing.anyways.eu/projects/genk/#15.77/50.9825/5.4888?sb=true&o=5.4933187,50.9834613&d=5.4825810,50.9828498&p=profile3

![image](https://user-images.githubusercontent.com/1128068/84776413-2f533380-afd8-11ea-8058-390a545ee191.png)

**Comment by pietervdvn** [comment]
https://www.openstreetmap.org/changeset/86768594
