### ISSUE TITLE
Route 2 change

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#47]
This route:

https://routing.anyways.eu/projects/genk/#14.72/50.9789/5.4980?sb=true&o=5.4932068,50.9766997&d=5.4996212,50.9828919&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84776605-6aedfd80-afd8-11ea-8140-9da670b078a4.png)

Has to change to this route:

https://routing.anyways.eu/projects/genk/#14.72/50.9789/5.4980?sb=true&o=5.4932068,50.9766997&d=5.4997522,50.9803981&p=profile3

![image](https://user-images.githubusercontent.com/1128068/84776695-8a852600-afd8-11ea-82ec-3437a16db7dd.png)

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/84795862-4e61bd80-aff8-11ea-9003-b662eb26185b.png)
Fixed

**Comment by pietervdvn** [comment]
Like this? The dark-blue piece is but a 'track'
![image](https://user-images.githubusercontent.com/1466478/84801599-abad3d00-afff-11ea-840d-2f460816ae89.png)

Also note that the part of route2 next to the stream, is currently 'but a path'

**Comment by xivk** [comment]
@pietervdvn I think so, it looks like the surface type is fine.

**Comment by xivk** [comment]
Fixed here:

https://www.openstreetmap.org/changeset/86988525#map=17/50.98097/5.49699
