### ISSUE TITLE
Access restriction destination only causing 'Groene Wandeling' detours

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#49]
https://routing.anyways.eu/projects/bikeforbrussels/#15.37/50.7748/4.3634?sb=true&o=4.3658065,50.7726864&d=4.3590411,50.7744292&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84801007-8b2cb500-aff6-11ea-8edf-a3f1ccff4381.png)

https://routing.anyways.eu/projects/bikeforbrussels/#16.71/50.77418/4.35602?sb=true&o=4.3543419,50.7737973&d=4.3559263,50.7736728&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84801099-a697c000-aff6-11ea-8742-68d1b1067bde.png)

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/84886158-53744a80-b094-11ea-823a-800c3abf78ab.png)


![image](https://user-images.githubusercontent.com/1466478/84886197-5ff8a300-b094-11ea-8ade-8caf025885a5.png)
