### ISSUE TITLE
Oneway bicycle missing

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#51]
https://routing.anyways.eu/projects/bikeforbrussels/#15.13/50.7973/4.3685?sb=true&o=4.3645034,50.7987021&d=4.3730739,50.7980039&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84804100-781be400-affa-11ea-8a7c-3badafb07726.png)

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/84886036-2889f680-b094-11ea-8a2b-8a3606330f3c.png)
