### ISSUE TITLE
Access tagging via park

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#52]
![image](https://user-images.githubusercontent.com/1128068/84804776-2c1d6f00-affb-11ea-8c7f-4fc28a2c6b42.png)

https://routing.anyways.eu/projects/bikeforbrussels/#15.88/50.8416/4.4413?sb=true&o=4.4436088,50.8410144&d=4.4417511,50.8421702&p=profile1

**Comment by xivk** [comment]
There was still a piece missing:

https://www.openstreetmap.org/changeset/86767405

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/85020632-e8e50c80-b170-11ea-8cc9-f6c2fb6429f5.png)
