### ISSUE TITLE
Handle highway=construction

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#53]
We need a way to handle highway=construction

This route is not possible because of construction:

https://routing.anyways.eu/projects/bikeforbrussels/#14.43/50.8567/4.4219?sb=true&o=4.4173059,50.8537517&d=4.4153025,50.8550967&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84805160-bebe0e00-affb-11ea-9138-1c00e52f43d8.png)

https://www.openstreetmap.org/changeset/80093939#map=16/50.8591/4.4110

**Comment by xivk** [comment]
We need to render the construction tagged highways I think, to make this clearer.

WDYT @pietervdvn ?

**Comment by pietervdvn** [comment]
Slap a 'bicycle=dismount' on them by default would do the trick IMHO ;p

This way, we would still go over it, but it'll cost a bit more so will only take it pays of (kindof)

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/85536346-4f57a800-b613-11ea-9df9-e05949a91481.png)
