### ISSUE TITLE
Destination only access

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#56]
https://routeplanner.bike.brussels/?sb=true&o=4.3317550,50.8767605&d=4.3979127,50.8699507&p=profile1#16.75/50.89592/4.38553?sb=true&o=4.3838056,50.8965165&d=4.3830179,50.8948413&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84934354-1aa59700-b0cf-11ea-9c8c-02ce6717c0e7.png)

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/85016633-6b1e0280-b16a-11ea-808e-c9a36f267948.png)
