### ISSUE TITLE
Bicycle access is not correct

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#57]
This route should go along the cycle network:

https://routeplanner.bike.brussels/?sb=true&o=4.3317550,50.8767605&d=4.3979127,50.8699507&p=profile1#15.82/50.9054/4.3905?sb=true&o=4.3883232,50.9072541&d=4.3869881,50.9046013&p=profile1

![image](https://user-images.githubusercontent.com/1128068/84934745-ab7c7280-b0cf-11ea-8cc1-747382510b1d.png)

This way for example cannot be accessed:

https://www.openstreetmap.org/way/207467480

**Comment by pietervdvn** [comment]
The problem here is not the mentioned way, but the roundabout. The 'cycleway=no' is wrongly interpreted as 'no access for cyclists'.

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/85536249-3949e780-b613-11ea-857b-64565a56a432.png)
