### ISSUE TITLE
Incorrect route

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#75]
![image](https://user-images.githubusercontent.com/1128068/93604198-59e0ce00-f9c5-11ea-98e2-d05b1b5d4951.png)

https://routing.anyways.eu/projects/bikeforbrussels/#16.24/50.97916/4.96778?sb=true&o=4.9645005,50.9793130&d=4.9709450,50.9797904&p=profile2

**Comment by pietervdvn** [comment]
The recreational profile dislikes primary roads, even if the cycleway is marked as 'track'. The commute profile does take the primary road.

TBH, I would be tempted to take this "incorrect" route (depending on the local circumstances)

**Comment by xivk** [comment]
https://github.com/anyways-open/routing-profiles/issues/53
