### ISSUE TITLE
Unexpected route

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#76]
![image](https://user-images.githubusercontent.com/1128068/93604534-c78cfa00-f9c5-11ea-9baa-70ab80d2471d.png)

https://routing.anyways.eu/projects/bikeforbrussels/#15.54/50.9800/4.9759?sb=true&o=4.9705157,50.9797767&d=4.9807657,50.9785318&p=profile2

**Comment by xivk** [comment]
Moved to https://github.com/anyways-open/routing-profiles/issues/53

**Comment by pietervdvn** [comment]
This behaviour makes sense, although it is an extreme example.

Some remarks:

- The primary road that is avoided, is a primary road which has cycleway=track, but also a 'bicycle:class=-2' added by thierry
- The roundabout is even worse, as it has the bicycle:class=-2 to. The profile 'comfort_safety' scores the roundabout quite bad - a priority around half a normal road.

So, yeah, it is [quite a bit longer (764m) ](https://routing.anyways.eu/projects/bikeforbrussels/#15.41/50.9800/4.9764?sb=true&o=4.9705157,50.9797767&d=4.9762467,50.9800243&p=profile2) then the [commute one](https://routing.anyways.eu/projects/bikeforbrussels/#15.41/50.9800/4.9764?sb=true&o=4.9705157,50.9797767&d=4.9762467,50.9800243&p=profile3), I do think that a recreational cyclist (especially older ladies) would make the detour like this. I can totally see my mum doing this ;)
