### ISSUE TITLE
Fix the rilaar detour

### ISSUE THREAD

**Issue by pietervdvn** [anyways-open/cycling-frontend#84]
- Add maxspeed to primary road
- Allow to take a primary road if there is a lower maxspeed then 30km/h

**Comment by pietervdvn** [comment]
https://www.openstreetmap.org/way/149611705#map=19/50.97426/4.89489

**Comment by xivk** [comment]
This about this route:

https://routeplanner.bike.brussels/#14.98/50.9761/4.8959?sb=true&o=4.8434491,50.9813596&d=4.9777172,50.9794781&p=profile2

![image](https://user-images.githubusercontent.com/1128068/102607399-88875580-4128-11eb-9904-275e6aa230fa.png)

**Comment by xivk** [comment]
Moved here: https://github.com/anyways-open/routing-profiles/issues/53
